export type LabelKind = 'manual' | 'auto'

export type Translator = (key: string, params?: Record<string, string | number>) => string

/**
 * Returns the display label for a polygon. For `manual` polygons the label
 * is the localized manual-label with the 1-based index substituted. For
 * `auto` polygons (autogenerated from the building register) the label is
 * the localized auto-label with no index.
 *
 * The translator is passed in so this module stays framework-agnostic and
 * does not depend on next-intl.
 */
export function polygonLabel(kind: LabelKind, index: number, t: Translator): string {
  if (kind === 'auto') return t('Polygon.autoLabel')
  return t('Polygon.manualLabel', { index })
}
